build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          - js-scrutinizer-run
      environment:
        php:
          version: 8.0
          ini:
            'extension' : 'imap'

      dependencies:
        before:
          #- 'sudo apt update'
          #- 'sudo apt-get install php8.0-imap -y'
          - 'composer require --dev johnpbloch/wordpress'
          #--ignore-platform-req=ext-imap'

filter:
  excluded_paths:
    - 'tests/*'
    - 'bin/*'
  dependency_paths:
    - wordpress/
checks:
  php:
    return_doc_comments: true
    simplify_boolean_return: true
    return_doc_comment_if_not_inferrable: true
    parameter_doc_comments: true
    param_doc_comment_if_not_inferrable: true
    overriding_parameter: true
    more_specific_types_in_doc_comments: true
    unused_variables: true
    no_exit: false
    foreach_traversable: true
    no_short_variable_names:
      minimum: '3'
    no_short_method_names:
      minimum: '3'
    no_long_variable_names:
      maximum: '20'
    no_goto: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
    unused_methods: false
  javascript:
    no_param_assign: false
    no_loop_var_assign: true
    no_else_return: true
    'check_switch_no_uncommented_fallthrough"': false
